version: '3'
services:

  fdk-organization-bff:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-organization-bff:test
    ports:
      - "8080:8080"
    environment:
      - ORGANIZATION_CATALOGUE_URI=http://wiremock:8080
      - DATA_BRREG_URI=http://wiremock:8080
      - FDK_PORTAL_URI=http://wiremock:8080
      - FDK_METADATA_QUALITY_URI=http://wiremock:8080
      - FDK_SPARQL_URI=http://wiremock:8080/sparql
    depends_on:
      - wiremock

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8000:8080"
    volumes:
      - ./mock_mappings/mappings:/home/wiremock/mappings
